# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ar_after_transaction}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Michael Grosser"]
  s.date = %q{2010-08-28}
  s.email = %q{grosser.michael@gmail.com}
  s.files = [
    "Gemfile",
     "Rakefile",
     "Readme.md",
     "VERSION",
     "ar_after_transaction.gemspec",
     "init.rb",
     "lib/ar_after_transaction.rb",
     "spec/ar_after_transaction_spec.rb",
     "spec/setup_database.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/grosser/ar_after_transaction}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Execute irreversible actions only when transactions are not rolled back}
  s.test_files = [
    "spec/setup_database.rb",
     "spec/spec_helper.rb",
     "spec/ar_after_transaction_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 0"])
  end
end

