source :rubygems

gem 'activerecord', '~>2', :require => 'active_record'

group :dev do
  gem 'rake'
  gem 'rspec', '~>2'
  gem 'jeweler'
  gem 'mysql'
  gem 'activesupport', '~>2', :require => 'active_support'
end
